name    'jalli-wget'
version '0.0.1'
source 'http://github.com/jalli/puppet-module-wget'
author 'jalli'
license 'GNU General Public License, Version 3.0'
summary 'Setup wget'
description 'Sets up wget command'
project_page 'http://github.com/jalli/puppet-module-wget'
